export const BACK_INDEX = 9;
export const SIDE_INDEX = 19;

// A TileValue is a map of mahjong unicode values to display name and other properties (suit, tileset index, number, etc).
export const TileValue: { [key: string]: { name: string; suit: string; index: number, number: number | null } } = {
    '🀇': { name: '1 of Characters', suit: 'Characters', index: 0, number: 1 },
    '🀈': { name: '2 of Characters', suit: 'Characters', index: 1, number: 2 },
    '🀉': { name: '3 of Characters', suit: 'Characters', index: 2, number: 3 },
    '🀊': { name: '4 of Characters', suit: 'Characters', index: 3, number: 4 },
    '🀋': { name: '5 of Characters', suit: 'Characters', index: 4, number: 5 },
    '🀌': { name: '6 of Characters', suit: 'Characters', index: 5, number: 6 },
    '🀍': { name: '7 of Characters', suit: 'Characters', index: 6, number: 7 },
    '🀎': { name: '8 of Characters', suit: 'Characters', index: 7, number: 8 },
    '🀏': { name: '9 of Characters', suit: 'Characters', index: 8, number: 9 },
    '🀐': { name: '1 of Bamboos', suit: 'Bamboos', index: 10, number: 1 },
    '🀑': { name: '2 of Bamboos', suit: 'Bamboos', index: 11, number: 2 },
    '🀒': { name: '3 of Bamboos', suit: 'Bamboos', index: 12, number: 3 },
    '🀓': { name: '4 of Bamboos', suit: 'Bamboos', index: 13, number: 4 },
    '🀔': { name: '5 of Bamboos', suit: 'Bamboos', index: 14, number: 5 },
    '🀕': { name: '6 of Bamboos', suit: 'Bamboos', index: 15, number: 6 },
    '🀖': { name: '7 of Bamboos', suit: 'Bamboos', index: 16, number: 7 },
    '🀗': { name: '8 of Bamboos', suit: 'Bamboos', index: 17, number: 8 },
    '🀘': { name: '9 of Bamboos', suit: 'Bamboos', index: 18, number: 9 },
    '🀙': { name: '1 of Dots', suit: 'Dots', index: 20, number: 1 },
    '🀚': { name: '2 of Dots', suit: 'Dots', index: 21, number: 2 },
    '🀛': { name: '3 of Dots', suit: 'Dots', index: 22, number: 3 },
    '🀜': { name: '4 of Dots', suit: 'Dots', index: 23, number: 4 },
    '🀝': { name: '5 of Dots', suit: 'Dots', index: 24, number: 5 },
    '🀞': { name: '6 of Dots', suit: 'Dots', index: 25, number: 6 },
    '🀟': { name: '7 of Dots', suit: 'Dots', index: 26, number: 7 },
    '🀠': { name: '8 of Dots', suit: 'Dots', index: 27, number: 8 },
    '🀡': { name: '9 of Dots', suit: 'Dots', index: 28, number: 9 },
    '🀀': { name: 'East Wind', suit: 'Winds', index: 30, number: null },
    '🀁': { name: 'South Wind', suit: 'Winds', index: 31, number: null },
    '🀂': { name: 'West Wind', suit: 'Winds', index: 32, number: null },
    '🀃': { name: 'North Wind', suit: 'Winds', index: 33, number: null },
    '🀄': { name: 'Red Dragon', suit: 'Dragons', index: 34, number: null },
    '🀅': { name: 'Green Dragon', suit: 'Dragons', index: 35, number: null },
    '🀆': { name: 'White Dragon', suit: 'Dragons', index: 36, number: null },
    // Flowers: (not used in all rule sets)
    '🀢': { name: 'Plum', suit: 'Flowers', index: 40, number: 1 },
    '🀣': { name: 'Orchid', suit: 'Flowers', index: 41, number: 2 },
    '🀥': { name: 'Chrysanthemum', suit: 'Flowers', index: 42, number: 3 },
    '🀤': { name: 'Bamboo', suit: 'Flowers', index: 43, number: 4 },
    // Seasons: (not used in all rule sets)
    '🀦': { name: 'Spring', suit: 'Seasons', index: 44, number: 1 },
    '🀧': { name: 'Summer', suit: 'Seasons', index: 45, number: 2 },
    '🀨': { name: 'Autumn', suit: 'Seasons', index: 46, number: 3 },
    '🀩': { name: 'Winter', suit: 'Seasons', index: 47, number: 4 },
};